### ISSUE TITLE
help to install mac os in mi notebook horizon i7

### ISSUE THREAD

**Issue by jyotirmoydotdev** [chadify/Mi-Notebook-14-Horizon-Edition-Hackintosh-EFI#1]
can you plz contact me and tell me how you have install mac os in mi notebook horizon i7 and how is the performance in it

Instagram : [jyotirmoy_barman_](https://www.instagram.com/jyotirmoy_barman_)
![IMG_20210524_235023](https://user-images.githubusercontent.com/64324524/119390551-d3feea80-bcea-11eb-8380-e555b6b3e0d8.jpg)

**Comment by jyotirmoydotdev** [comment]
or  you  can  tell me here  only if you don't have an Instagram account

**Comment by chadify** [comment]
> or you can tell me here only if you don't have an Instagram account

You can join us on discord https://discord.gg/bMJHuu5Y. You may ask for help there.
